"""
Error codes cho toàn bộ hệ thống.
Dùng structured error codes thay vì plain text để frontend tự handle.
"""

class ErrorCodes:
    # Auth errors (1xxx)
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_USER_BLOCKED = "AUTH_USER_BLOCKED"
    AUTH_OTP_INVALID = "AUTH_OTP_INVALID"
    AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED"
    AUTH_OTP_EXCEEDED_ATTEMPTS = "AUTH_OTP_EXCEEDED_ATTEMPTS"
    AUTH_PHONE_ALREADY_EXISTS = "AUTH_PHONE_ALREADY_EXISTS"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    AUTH_INVALID_PASSWORD = "AUTH_INVALID_PASSWORD"

    # Course errors (2xxx)
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
    COURSE_ALREADY_EXISTS = "COURSE_ALREADY_EXISTS"
    COURSE_SLUG_DUPLICATED = "COURSE_SLUG_DUPLICATED"
    COURSE_CANNOT_DELETE_PUBLISHED = "COURSE_CANNOT_DELETE_PUBLISHED"
    COURSE_NOT_PUBLISHED = "COURSE_NOT_PUBLISHED"
    COURSE_INVALID_LEVEL = "COURSE_INVALID_LEVEL"
    COURSE_SECTION_NOT_FOUND = "COURSE_SECTION_NOT_FOUND"
    COURSE_UNIT_NOT_FOUND = "COURSE_UNIT_NOT_FOUND"
    COURSE_BLOCK_NOT_FOUND = "COURSE_BLOCK_NOT_FOUND"
    COURSE_TRANSLATION_NOT_FOUND = "COURSE_TRANSLATION_NOT_FOUND"
    COURSE_TRANSLATION_EXISTS = "COURSE_TRANSLATION_EXISTS"

    # Category errors (25xx)
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"
    CATEGORY_TRANSLATION_FAILED = "CATEGORY_TRANSLATION_FAILED"
    CATEGORY_CREATE_FAILED = "CATEGORY_CREATE_FAILED"
    CATEGORY_DETAIL_FAILED = "CATEGORY_DETAIL_FAILED"
    CATEGORY_UPDATE_FAILED = "CATEGORY_UPDATE_FAILED"
    CATEGORY_DELETE_FAILED = "CATEGORY_DELETE_FAILED"
    CATEGORY_HAS_COURSES = "CATEGORY_HAS_COURSES"

    # Coin errors (3xxx)
    COIN_INSUFFICIENT_BALANCE = "COIN_INSUFFICIENT_BALANCE"
    COIN_PACKAGE_NOT_FOUND = "COIN_PACKAGE_NOT_FOUND"
    COIN_PURCHASE_FAILED = "COIN_PURCHASE_FAILED"
    COIN_REFUND_FAILED = "COIN_REFUND_FAILED"
    COIN_TRANSACTION_NOT_FOUND = "COIN_TRANSACTION_NOT_FOUND"
    COIN_INVALID_AMOUNT = "COIN_INVALID_AMOUNT"
    COIN_PAYMENT_FAILED = "COIN_PAYMENT_FAILED"
    COIN_PAYMENT_TIMEOUT = "COIN_PAYMENT_TIMEOUT"
    COIN_ORDER_NOT_FOUND = "COIN_ORDER_NOT_FOUND"
    COIN_ORDER_EXPIRED = "COIN_ORDER_EXPIRED"
    COIN_ORDER_ALREADY_PAID = "COIN_ORDER_ALREADY_PAID"

    # User errors (4xxx)
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_PROFILE_INCOMPLETE = "USER_PROFILE_INCOMPLETE"
    USER_INVALID_ROLE = "USER_INVALID_ROLE"
    USER_ROLE_NOT_FOUND = "USER_ROLE_NOT_FOUND"

    # Validation errors (5xxx)
    VALIDATION_INVALID_INPUT = "VALIDATION_INVALID_INPUT"
    VALIDATION_MISSING_FIELD = "VALIDATION_MISSING_FIELD"
    VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT"
    VALIDATION_OUT_OF_RANGE = "VALIDATION_OUT_OF_RANGE"
    VALIDATION_FILE_TOO_LARGE = "VALIDATION_FILE_TOO_LARGE"
    VALIDATION_UNSUPPORTED_FILE_TYPE = "VALIDATION_UNSUPPORTED_FILE_TYPE"

    # System errors (9xxx)
    SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR"
    SYSTEM_DATABASE_ERROR = "SYSTEM_DATABASE_ERROR"
    SYSTEM_CACHE_ERROR = "SYSTEM_CACHE_ERROR"
    SYSTEM_STORAGE_ERROR = "SYSTEM_STORAGE_ERROR"
    SYSTEM_EXTERNAL_API_ERROR = "SYSTEM_EXTERNAL_API_ERROR"
    SYSTEM_RATE_LIMITED = "SYSTEM_RATE_LIMITED"
    SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE"
